name: submit_dicoding_dictionary
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  eva_icons_flutter: ^3.1.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  share_plus: ^4.0.3
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/lottie/
  uses-material-design: true
