name: submit_dicoding_dictionary
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true
 